"$schema" = "https://starship.rs/config-schema.json"

format = """
[](cyan)\
$os\
$username\
$hostname\
[](fg:cyan bg:purple)\
$directory\
[](purple) \
$git_branch\
$git_status\
$c\
$cpp\
$python\
$nodejs\
$conda\
$cmd_duration\
$shell\
$time\
$status\
$jobs\
$line_break\
$character"""

# ANSI colors follow Ghostty or the active VS Code Profile.
add_newline = false

[os]
disabled = false
style = "fg:black bg:cyan"
format = "[$symbol]($style)"

[os.symbols]
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"
Ubuntu = "󰕈"

[username]
show_always = true
style_user = "fg:black bg:cyan"
style_root = "fg:black bg:red"
format = "[ $user ]($style)"

[directory]
style = "fg:black bg:purple"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:black bg:yellow"
format = "[](yellow)[ $symbol $branch ]($style)[](yellow) "

[git_status]
style = "fg:black bg:red"
format = "[](red)[ $all_status$ahead_behind ]($style)[](red) "

[c]
symbol = ""
style = "fg:black bg:green"
format = "[](green)[ $symbol $version ]($style)[](green) "

[cpp]
symbol = ""
style = "fg:black bg:green"
format = "[](green)[ $symbol $version ]($style)[](green) "

[python]
symbol = ""
style = "fg:black bg:blue"
format = "[](blue)[ $symbol $version ]($style)[](blue) "

[nodejs]
symbol = ""
style = "fg:black bg:green"
format = "[](green)[ $symbol $version ]($style)[](green) "

[conda]
symbol = ""
style = "fg:black bg:blue"
format = "[](blue)[ $symbol $environment ]($style)[](blue) "
ignore_base = false

[cmd_duration]
min_time = 2000
show_milliseconds = false
show_notifications = true
min_time_to_notify = 45000
style = "fg:black bg:bright-blue"
format = "[](bright-blue)[  $duration ]($style)[](bright-blue) "

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold bright-blue)"
vimcmd_replace_symbol = "[❮](bold bright-blue)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[hostname]
ssh_only = false
trim_at = "."
style = "fg:black bg:cyan"
format = "[@$hostname ]($style)"

[shell]
disabled = false
style = "cyan"
format = "[$indicator]($style) "

[time]
disabled = false
time_format = "%H:%M:%S"
style = "fg:black bg:cyan"
format = "[](cyan)[  $time ]($style)[](cyan) "

[status]
disabled = false
style = "bold red"
format = "[✘ $status]($style) "

[jobs]
number_threshold = 1
symbol_threshold = 1
style = "bold yellow"
format = "[⚙ $number]($style) "
