"$schema" = "https://starship.rs/config-schema.json"

format = """
[](mauve)\
$os\
$username\
[](fg:mauve bg:peach)\
$directory\
[](peach) \
$git_branch\
$git_status\
$c\
$cpp\
$python\
$nodejs\
$conda\
$cmd_duration\
$line_break\
$character"""

palette = "catppuccin_mocha"
add_newline = false

[os]
disabled = false
style = "fg:crust bg:mauve"
format = "[$symbol]($style)"

[os.symbols]
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"
Ubuntu = "󰕈"

[username]
show_always = true
style_user = "fg:crust bg:mauve"
style_root = "fg:crust bg:red"
format = "[ $user ]($style)"

[directory]
style = "fg:crust bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:crust bg:yellow"
format = "[](yellow)[ $symbol $branch ]($style)[](yellow) "

[git_status]
style = "fg:crust bg:red"
format = "[](red)[ $all_status$ahead_behind ]($style)[](red) "

[c]
symbol = ""
style = "fg:crust bg:green"
format = "[](green)[ $symbol $version ]($style)[](green) "

[cpp]
symbol = ""
style = "fg:crust bg:green"
format = "[](green)[ $symbol $version ]($style)[](green) "

[python]
symbol = ""
style = "fg:crust bg:blue"
format = "[](blue)[ $symbol $version ]($style)[](blue) "

[nodejs]
symbol = ""
style = "fg:crust bg:green"
format = "[](green)[ $symbol $version ]($style)[](green) "

[conda]
symbol = ""
style = "fg:crust bg:sapphire"
format = "[](sapphire)[ $symbol $environment ]($style)[](sapphire) "
ignore_base = false

[cmd_duration]
min_time = 2000
show_milliseconds = false
show_notifications = true
min_time_to_notify = 45000
style = "fg:crust bg:lavender"
format = "[](lavender)[  $duration ]($style)[](lavender) "

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold lavender)"
vimcmd_replace_symbol = "[❮](bold lavender)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
