#!/bin/bash

options=(
  style=round
  width=4.0
  hidpi=on
  active_color=0xffb4befe
  inactive_color=0x00000000
  blur_radius=1
  blacklist="sketchybar,Notification Center,Control Center"
)

borders "${options[@]}"
