#!/bin/bash

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/borders"
source "$config_dir/theme-colors.sh" || exit 1

options=(
  style=round
  width=10.0
  hidpi=on
  active_color="$BORDER_ACTIVE"
  inactive_color="$BORDER_INACTIVE"
  blacklist="sketchybar,Notification Center,Control Center"
)

borders "${options[@]}"
